---
- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    update_cache: yes 
    state: latest
    force_apt_get: True

- name: Install System Tools
  apt:
    name: ['build-essential', 'gcc', 'apt-transport-https', 'ca-certificates', 'software-properties-common', 'linux-headers-amd64', 'make', 'perl', 'ntp']
    update_cache: yes 
    state: latest

- name: Install Graphical Mode
  apt:
    name: task-gnome-desktop
    update_cache: yes 
    state: present

- name: Adding Python requirements
  apt: 
    name: ['python3', 'python3-apt', 'python3-dev', 'python3-pip', 'python3-virtualenv', 'python3-setuptools'] 
    update_cache: yes 
    state: present

- name: Adding some tools
  apt: 
    name: ['htop', 'iotop', 'mlocate', 'net-tools', 'nmap', 'whois', 'w3m', 'zip', 'meld'] 
    update_cache: yes 
    state: present
    
- name: Editing TOOLS
  apt:
    name: ['terminator', 'emacs', 'yaml-mode', 'tree', 'git', 'ack', 'wget', 'keepassxc']
    update_cache: yes 
    state: present

    
